CREATE TABLE forum (
    id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sujet VARCHAR(255) NOT NULL,
    auteur VARCHAR(60) NOT NULL,
    text TEXT NOT NULL,
    date DATETIME NOT NULL,
    UNIQUE(subject)
);